# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb/price_update.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pb/price_update.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x15pb/price_update.proto\" \n\x0bPriceUpdate\x12\x11\n\ttimestamp\x18\x01 \x01(\tb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PRICEUPDATE = _descriptor.Descriptor(
  name='PriceUpdate',
  full_name='PriceUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='PriceUpdate.timestamp', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=57,
)

DESCRIPTOR.message_types_by_name['PriceUpdate'] = _PRICEUPDATE

PriceUpdate = _reflection.GeneratedProtocolMessageType('PriceUpdate', (_message.Message,), dict(
  DESCRIPTOR = _PRICEUPDATE,
  __module__ = 'pb.price_update_pb2'
  # @@protoc_insertion_point(class_scope:PriceUpdate)
  ))
_sym_db.RegisterMessage(PriceUpdate)


# @@protoc_insertion_point(module_scope)
